### ISSUE TITLE
Unable to find measure_scores.py

### ISSUE THREAD

**Issue by dfayzur** [sIncerass/prag_generation#1]
Hello,

Thank you very much for the code. I was trying to run the code. But there is a file (measure_scores.py) missing. Would you please add the file to the repo.

**Comment by sIncerass** [comment]
Sure, I upload the "e2e-metrics" directory. To use the "measure_score.py", you can run as

> "python2 measure_scores.py ../data/devset.csv.multi-ref ../experiments/select_model_v1/weights.epoch8.devset.predictions.txt_incre_0.2_new"

**Comment by sIncerass** [comment]
To reproduce my experiment, you can just use the model in the "experiment" directory since we only change the inference process.

**Comment by dfayzur** [comment]
Thank you very much for adding measure_scores.py in the repo. The training and prediction is working without any issues. Closing it.
