### ISSUE TITLE
Missing lines in predictions

### ISSUE THREAD

**Issue by ProKil** [sIncerass/prag_generation#2]
Thank you for sharing your codes! I used [tuetschek/e2e-metrics](https://github.com/tuetschek/e2e-metrics) as the evaluation protocol. But while I ran `python run_experiment.py my_train.yaml`, the following error occured. 
```
Traceback (most recent call last):
  File ".../e2e-metrics/measure_scores.py", line 344, in <module>
    data_src, data_ref, data_sys = load_data(args.ref_file, args.sys_file, args.src_file)
  File ".../e2e-metrics/measure_scores.py", line 193, in load_data
    assert(len(data_ref) == len(data_sys) == len(data_src))
```

I checked `predictions.epoch1`, and found that it has fewer lines (546) than the E2E challenge [official baseline](https://github.com/UKPLab/e2e-nlg-challenge-2017) (547).

**Comment by sIncerass** [comment]
Thanks for reaching out.
Yeah, this is something related to the original code. Can you use the run_fw.py file for evaluation instead. The beam_size and alpha will be the parameters that you can tune on.
I will check that today and do more cleaning for it.

**Comment by ProKil** [comment]
Thanks for your reply. I tried `python run_fw.py my_train.yaml`, but this time a different error:
```
Traceback (most recent call last):
  File "/.../e2e-metrics/measure_scores.py", line 348, in <module>
    evaluate(data_src, data_ref, data_sys, args.table, args.header, args.sys_file, args.python)
  File "/.../e2e-metrics/measure_scores.py", line 203, in evaluate
    coco_eval = run_coco_eval(data_ref, data_sys)
  File "/.../e2e-metrics/measure_scores.py", line 291, in run_coco_eval
    coco_eval.evaluate()
  File "/.../e2e-metrics/pycocoevalcap/eval.py", line 25, in evaluate
    res[imgId] = self.cocoRes.imgToAnns[imgId]
KeyError: 'inst-546'
```

**Comment by sIncerass** [comment]
Sure, I will check that today and response as soon as possible.

**Comment by sIncerass** [comment]
Can you specify the dataset you are using? I provide them in the data directory.

**Comment by sIncerass** [comment]
It should now be ok for training.

**Comment by ProKil** [comment]
Thank you for the quick fix! The training process now works with no errors.

**Comment by ProKil** [comment]
Evaluation on the test data experienced `IndexError: list index out of range`. I would appreciate it if you could also fix this one. Thank you very much!

```
Traceback (most recent call last):
  File "run_fw.py", line 104, in <module>
    run(config_d)
  File "run_fw.py", line 73, in run
    predicted_ids, fw_beam = evaluator.evaluate_model(model, data.dev[0], data.uni_mr['dev'], beam_size=beam_siz
e, alpha=alpha)
  File "/.../prag_generation/e2e-incre/components/evaluator/e2e_evaluator.py", line 93, in
 evaluate_model
    p = mask_(snt_ids, dis_ids, dev_data)
  File "/.../prag_generation/e2e-incre/components/evaluator/e2e_evaluator.py", line 88, in mask_
    outs[ cur_f ] = Counter(pp).most_common()[0][0]
IndexError: list index out of range
```

**Comment by sIncerass** [comment]
This was already fixed. Thanks for approaching.
